"""Create a fresh slides project from a program-generated Bypage baseline."""
from __future__ import annotations

import argparse
import hashlib
import json
import mimetypes
import os
import re
import shutil
import subprocess
import tempfile
from pathlib import Path

from init_svg_project import CANONICAL_DIRS, STARTER_FILES
from prepare_source_material import image_size

KEY = re.compile(r'[A-Za-z][A-Za-z0-9_-]{0,63}')


def feedback_source_hash(copy, audit, manifest):
    skill = Path(__file__).resolve().parents[1]
    candidates = (skill.parent / 'planners-bypage', skill.parent.parent / '02-content-assembly/planners-bypage')
    for bypage in candidates:
        contract = bypage / 'scripts/lib/review-source-hash.mjs'
        if contract.is_file():
            result = subprocess.run(
                ['node', str(contract)], input=json.dumps({
                    'copy': copy.decode('utf-8'), 'audit': audit.decode('utf-8'),
                    'manifest': manifest.decode('utf-8'),
                }), text=True, capture_output=True, timeout=30, check=True)
            return result.stdout.strip()
    raise ValueError('Bypage review-source-hash contract is required for production import')


def checked(binding):
    if not isinstance(binding, dict) or not isinstance(binding.get('path'), str):
        raise ValueError('Invalid Bypage file binding')
    if not isinstance(binding.get('sha256'), str) or not re.fullmatch(r'[0-9a-f]{64}', binding['sha256']):
        raise ValueError('Bypage binding needs a SHA-256 digest')
    path = Path(binding['path'])
    if not path.is_absolute() or any(part.startswith('.env') for part in path.parts):
        raise ValueError('Bypage binding needs a canonical non-environment path')
    path = path.resolve(strict=True)
    if any(part.startswith('.env') for part in path.parts):
        raise ValueError('Environment files are not Bypage inputs')
    if not path.is_file():
        raise ValueError('Bypage binding needs a regular file')
    data = path.read_bytes()
    if hashlib.sha256(data).hexdigest() != binding.get('sha256'):
        raise ValueError(f'Bypage binding changed: {path}')
    return path, data


def import_bypage(production, project):
    production = Path(production).absolute()
    if any(part.startswith('.env') for part in production.parts):
        raise ValueError('Environment files are not Bypage inputs')
    production = production.resolve(strict=True)
    if any(part.startswith('.env') for part in production.parts):
        raise ValueError('Environment files are not Bypage inputs')
    raw = production.read_bytes()
    payload = json.loads(raw)
    if payload.get('version') != 'bypage-production/1' or payload.get('route') != 'slides':
        raise ValueError('Expected bypage-production/1 slides export')
    upstream = payload.get('upstream', {})
    for name in ('copy', 'memory', 'source_index', 'audit', 'feedback', 'asset_manifest',
                 'deliverable', 'delivered_asset_manifest'):
        if name not in upstream:
            raise ValueError(f'Missing canonical Bypage binding: {name}')
    files = {name: checked(record) for name, record in upstream.items()}
    audit = json.loads(files['audit'][1])
    if Path(audit['artifact']['path']).resolve() != files['copy'][0] or audit['artifact']['sha256'] != upstream['copy']['sha256']:
        raise ValueError('Audit does not bind the original Bypage baseline')
    source_path = (files['audit'][0].parent / audit['source_index']['path']).resolve()
    if source_path != files['source_index'][0]:
        raise ValueError('Audit source index differs from Bypage baseline')
    feedback = json.loads(files['feedback'][1])
    feedback_hash = feedback_source_hash(files['copy'][1], files['audit'][1], files['asset_manifest'][1])
    if feedback.get('overall_decision') != 'approve' or feedback.get('source_sha256') != feedback_hash:
        raise ValueError('Complete-copy feedback does not bind the baseline/audit/asset manifest')
    pages = payload.get('pages', [])
    order = payload.get('order', [])
    keys = [page.get('page_key') for page in pages]
    if not pages or len(set(keys)) != len(keys) or keys != order or any(not KEY.fullmatch(str(key)) for key in keys):
        raise ValueError('Bypage page identities must uniquely match declared order')
    project = Path(project).resolve()
    if project.exists() and any(project.iterdir()):
        raise ValueError('Import needs an empty project; existing workbench edits are preserved')
    project.parent.mkdir(parents=True, exist_ok=True)
    staging = Path(tempfile.mkdtemp(prefix=f'.{project.name}.bypage-', dir=project.parent))
    try:
        for directory in CANONICAL_DIRS:
            (staging / directory).mkdir(parents=True, exist_ok=True)
        for name, text in STARTER_FILES.items():
            (staging / name).write_text(text, encoding='utf-8')
        result_pages, assets = [], {}
        for page in pages:
            content = page['content']
            notes = page.get('notes', '')
            production_notes = page.get('production_notes', '')
            page_assets = []
            for asset in page.get('assets', []):
                path, data = checked(asset)
                identity = asset.get('asset_id') or 'attachment-' + asset['sha256'][:24]
                if not isinstance(identity, str) or not identity.strip():
                    raise ValueError(f'Invalid upstream asset identity: {identity}')
                if identity in assets and assets[identity]['sha256'] != asset['sha256']:
                    raise ValueError(f'Ambiguous upstream asset identity {identity}: different byte variants need explicit page occurrence mapping')
                relative = f'_internal/00_project/source/assets/{asset["sha256"]}{path.suffix}'
                destination = staging / relative
                destination.write_bytes(data)
                record = {**asset, 'asset_id': identity, 'path': relative, 'original_path': str(path)}
                width, height = image_size(data, path.suffix)
                record.update(normalized_path=relative, source_kind='bypage', original_ref=asset['reference'],
                              mime_type=mimetypes.guess_type(path.name)[0] or 'application/octet-stream',
                              width_px=width, height_px=height,
                              aspect_ratio=round(width / height, 6) if width and height else None,
                              alt='', external=False,
                              occurrences=[{'original_ref': asset['reference'], 'alt': ''}])
                assets.setdefault(identity, record)
                page_assets.append(identity)
                content = content.replace(asset['reference'], relative)
                production_notes = production_notes.replace(asset['reference'], relative)
            result_pages.append({
                'page_key': page['page_key'], 'mode': '读', 'title': page['title'],
                'content': content, 'notes': notes, 'production_notes': production_notes,
                'sources': page.get('sources', ''), 'source_assets': list(dict.fromkeys(page_assets)),
                'bypage_identity': page['identity'], 'bypage_page_number': page['page_number'],
                'main_message': page.get('main_message', ''),
                'upstream_provenance': {'kind': 'upstream-baseline', 'copy': upstream['copy'],
                                        'audit': upstream['audit'], 'audit_scope': 'original-bypage-copy'},
            })
        def write(relative, data):
            (staging / relative).write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
        write('_internal/01_content/page_content.json', {
            'project': project.name, 'source_path': upstream['deliverable']['path'],
            'source_assets_path': '_internal/00_project/source/source_assets.json', 'pages': result_pages,
        })
        write('_internal/00_project/source/source_assets.json', {
            'source_type': 'bypage', 'original_source': upstream['copy']['path'],
            'normalized_source': upstream['deliverable']['path'],
            'image_count': len(assets), 'assets': list(assets.values()),
        })
        manifest = json.loads((staging / '_internal/00_project/page_manifest.json').read_text())
        manifest.update(route='slides', input_binding={
            'version': 'bypage-production/1', 'production_path': str(production),
            'production_sha256': hashlib.sha256(raw).hexdigest(), 'upstream': upstream,
            'provenance': payload['provenance'],
        })
        write('_internal/00_project/page_manifest.json', manifest)
        if project.exists():
            project.rmdir()
        os.replace(staging, project)
    finally:
        if staging.exists():
            shutil.rmtree(staging)
    return {'project': str(project), 'order': order, 'upstream': upstream}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('project', type=Path)
    parser.add_argument('--production', type=Path, required=True)
    args = parser.parse_args()
    print(json.dumps(import_bypage(args.production, args.project), ensure_ascii=False))


if __name__ == '__main__':
    main()
